#!/usr/bin/env bash
#
# GnomeBeautifier — semantic wallpaper distributor.
#
# Replaces setup-wallpapers.sh's "every image into every bucket" distribution
# with a hand-curated classification: each known wallpaper file goes only to
# the bucket(s) that visually match it (weather and, when applicable, time of
# day). Images not in the table go to default/ so nothing gets lost.
#
# The mapping below was generated by viewing each staged image and assigning
# the best-fit (weather_bucket, optional_time_bucket) pairs. Multi-classified
# entries appear in multiple buckets via hardlinks (no extra disk cost).
#
# Run this AFTER setup-wallpapers.sh has staged source images:
#   bash scripts/setup-wallpapers.sh --no-install   # stages into ~/.cache/...
#   bash scripts/classify-wallpapers.sh             # this script
#
# Usage:
#   bash scripts/classify-wallpapers.sh [--root <path>] [--copy]
#
# By default uses hardlinks (instant, near-zero disk usage) and falls back to
# copies when the staging and root are on different filesystems.

set -euo pipefail

WALL_ROOT="${GNOMEBEAUTIFIER_WALLPAPER_ROOT:-$HOME/Pictures/Weather-Wallpapers}"
STAGING="$HOME/.cache/gnomebeautifier/staging-wallpapers"
USE_COPY=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)  WALL_ROOT="$2"; shift 2 ;;
        --copy)  USE_COPY=1; shift ;;
        -h|--help) sed -n '1,30p' "$0"; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

WEATHER_BUCKETS=(clear clouds rain storm snow fog night default)
TIME_BUCKETS=(morning afternoon evening night)

# -----------------------------------------------------------------------------
# Classification table.
#
# Format (one per line):  <filename> | <bucket>[/<time>] [;<bucket>[/<time>]]*
#
# A trailing /<time> places the image in <bucket>/<time>/ (time-of-day variant).
# No /<time> places it in <bucket>/ (any time).
# Semicolon-separated entries multi-classify the image (hardlinked into each).
# -----------------------------------------------------------------------------

CLASSIFICATION=$(cat <<'EOF'
sys-160818-rgrd-a1_by_pierre_cante.jpg|default/afternoon
sys-1_by_the5heepdev.jpg|fog/evening;clouds/evening
sys-2_by_the5heepdev.jpg|night/night;clear/night
sys-Greenish_by_EstebanMitnick.jpg|default
sys-Resolute_Raccoon_Wallpaper_Dimmed_3840x2160.png|default/evening
sys-Resolute_Raccoon_Wallpaper_Light_3840x2160.png|default/morning
sys-abstract-lock-screen.jpg|default
sys-cnusr25-Simple_Raccoon_Dark.png|default/evening
sys-cnusr25-Simple_Raccoon_Light.png|clear/morning;clear/afternoon
sys-endycal-Flying_Boxes_Dark.png|default/evening
sys-endycal-Flying_Boxes_Light.png|default/afternoon
sys-ezspain-Ubuntu_Coffee_Mug_Dark.png|default/evening
sys-ezspain-Ubuntu_Coffee_Mug_Light.png|default/afternoon
sys-iryge-Anomaly.png|default/evening
sys-jdituicha-raccoon1-dark.jpg|default/evening
sys-jdituicha-raccoon1-light.jpg|default/afternoon
sys-manuej-Vor.jpg|default/evening
sys-mendhak-Bluebells_Suspended_In_Time.jpg|clear/morning;clear
sys-mendhak-Red_Acer.jpg|default/evening;clouds/evening
sys-mizuno-as-Big_Dipper.jpg|night/night;clear/night
sys-mizuno-as-Winter_Grand_Triangle.jpg|night/night;clear/night
sys-moskalenko-v-Low_poly_Raccoon_Dark.webp|default/evening
sys-moskalenko-v-Low_poly_Raccoon_Light.webp|default/afternoon
sys-moskalenko-v-Low_poly_Raccoon_Very_Dark.webp|night/night
sys-moskalenko-v-Snowy_Ubuntu_Dark.webp|night/night
sys-moskalenko-v-Snowy_Ubuntu_Light.webp|snow/morning;snow;default/morning
sys-osselo-Ask_a_friend.jpg|default/evening
sys-raindrops_on_a_maple_leaf_by_markus_rossel.jpg|rain
sys-rubenslp-Twin_brothers.png|default/evening
sys-snowy_pines_above_planica_by_jan_makovecki.jpg|snow;clouds;fog
sys-sochi_krasnaya_polyana_mountains_by_alexander_lyubavin.jpg|clouds/evening;fog/evening
sys-spirales_by_victor_mussard.jpg|clear/afternoon;clear
sys-trucioli_by_filippo_de_angeli.jpg|default
sys-ubuntu-wallpaper-d.png|default/evening
sys-ubwp_2327_by_rigazilla.jpg|default
sys-vale1ntin0omf-Electric_Veins_of_the_Storm.jpg|storm/night;storm
sys-vnc-d.png|night/night;default/night
sys-vnc-l.png|default
sys-wall27-2016_by_k_alam1985.jpg|clouds/afternoon;default
sys-warty-final-ubuntu.png|default
EOF
)

# -----------------------------------------------------------------------------

log() { echo "$@"; }

step() { echo; log "===== $* ====="; }

if [[ ! -d "$STAGING" ]]; then
    echo "ERROR: staging directory missing ($STAGING)." >&2
    echo "Run scripts/setup-wallpapers.sh first to stage source images." >&2
    exit 1
fi

step "GnomeBeautifier semantic classifier"
log "Staging:   $STAGING"
log "Root:      $WALL_ROOT"
log "Mode:      $([[ $USE_COPY -eq 1 ]] && echo 'copy' || echo 'hardlink (with copy fallback)')"

# -----------------------------------------------------------------------------
# Rebuild fresh bucket directories (preserves user-curated files? No — for a
# clean classification we want to start from a known state. The script is
# idempotent: rerunning produces the same content. Users who hand-curated
# specific files should keep them in a SEPARATE root.)
# -----------------------------------------------------------------------------

step "Reset bucket tree under $WALL_ROOT"
for b in "${WEATHER_BUCKETS[@]}"; do
    rm -rf "$WALL_ROOT/$b"
    mkdir -p "$WALL_ROOT/$b"
    for t in "${TIME_BUCKETS[@]}"; do
        mkdir -p "$WALL_ROOT/$b/$t"
    done
done

# -----------------------------------------------------------------------------
# Place a file at a single destination path. Tries hardlink first (works only
# on the same filesystem), falls back to copy.
# -----------------------------------------------------------------------------

place() {
    local src="$1" dst="$2"
    if [[ $USE_COPY -eq 1 ]]; then
        cp -f "$src" "$dst"
        return
    fi
    if ln -f "$src" "$dst" 2>/dev/null; then
        return
    fi
    cp -f "$src" "$dst"
}

# -----------------------------------------------------------------------------
# Walk the classification table; place each known image. Track which files
# from staging were claimed.
# -----------------------------------------------------------------------------

declare -A CLAIMED=()
PLACED=0
SKIPPED=0

while IFS='|' read -r fname targets; do
    [[ -z "$fname" || "$fname" =~ ^[[:space:]]*# ]] && continue
    src="$STAGING/$fname"
    if [[ ! -f "$src" ]]; then
        SKIPPED=$((SKIPPED+1))
        continue
    fi
    CLAIMED["$fname"]=1
    # Targets are semicolon-separated bucket[/time] pairs.
    IFS=';' read -ra paths <<< "$targets"
    for p in "${paths[@]}"; do
        bucket="${p%%/*}"
        time="${p#*/}"
        if [[ "$bucket" == "$time" ]]; then
            time=""
        fi
        dst_dir="$WALL_ROOT/$bucket"
        if [[ -n "$time" ]]; then
            dst_dir="$dst_dir/$time"
        fi
        mkdir -p "$dst_dir"
        place "$src" "$dst_dir/$fname"
        PLACED=$((PLACED+1))
    done
done <<< "$CLASSIFICATION"

# -----------------------------------------------------------------------------
# Unclassified staged files → drop in default/ so they're still reachable.
# -----------------------------------------------------------------------------

step "Catch unclassified staged files into default/"
EXTRAS=0
while IFS= read -r src; do
    fname="$(basename "$src")"
    [[ -n "${CLAIMED[$fname]:-}" ]] && continue
    place "$src" "$WALL_ROOT/default/$fname"
    EXTRAS=$((EXTRAS+1))
done < <(find "$STAGING" -maxdepth 1 -type f)

# -----------------------------------------------------------------------------
# Summary.
# -----------------------------------------------------------------------------

step "Bucket summary"
for b in "${WEATHER_BUCKETS[@]}"; do
    n_root=$(find "$WALL_ROOT/$b" -maxdepth 1 -type f 2>/dev/null | wc -l)
    n_total=$(find "$WALL_ROOT/$b" -type f 2>/dev/null | wc -l)
    line=$(printf "  %-8s %3d files (root=%d)" "$b" "$n_total" "$n_root")
    sub=""
    for t in "${TIME_BUCKETS[@]}"; do
        nt=$(find "$WALL_ROOT/$b/$t" -maxdepth 1 -type f 2>/dev/null | wc -l)
        if [[ $nt -gt 0 ]]; then
            sub="$sub  $t=$nt"
        fi
    done
    echo "${line}${sub}"
done

step "Done"
log "Placed:        $PLACED entries from $((PLACED-EXTRAS)) classified files"
log "Extras:        $EXTRAS unclassified files dropped into default/"
log "Skipped:       $SKIPPED classified files missing from staging (expected if you haven't installed kde-wallpapers yet)"
log ""
log "If a bucket looks too sparse:"
log "  - Drop more wallpapers manually into ~/Pictures/Weather-Wallpapers/<bucket>/[<time>/]"
log "  - Or install plasma-workspace-wallpapers to seed the KDE collection,"
log "    then rerun:  bash scripts/setup-wallpapers.sh && bash scripts/classify-wallpapers.sh"
